name: flutter_testing_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  singular_flutter_sdk: ^1.2.1
  app_tracking_transparency: ^2.0.4
  firebase_core: ^2.8.0
  app_set_id: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
   - family: Poppins
     fonts:
       - asset: fonts/Poppins-Regular.ttf
       - asset: fonts/Poppins-Medium.ttf